---
# tasks file for nginx

- name: Install nginx
  yum: name=nginx state=present
  notify: restart nginx

- name: Remove default configuration file
  file:
    path: /etc/nginx/nginx.conf.default
    state: absent

- name: Make sure conf.d/ exists
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {
      src: "nginx.conf.j2",
      dest: "/etc/nginx/nginx.conf"
      }

- name: Create dhparam.pem if not exists
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048 creates=/etc/ssl/dhparam.pem

- name: Remove nginx access logs if any
  shell: find /var/log/nginx/ -name "*access*" -print0 | xargs --no-run-if-empty -0 rm
  register: rm_result
  changed_when: 'rm_result.stdout != ""'

- name: Create ssl directory
  file:
    path: /etc/ssl/hackerspace.gr/
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    - ssl

- name: Copy ssl cerificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0400
  with_items:
    - {
      src: "ssl/hackerspace.gr/ssl-unified.crt",
      dest: "{{ ssl_cert }}"
      }
    - {
      src: "ssl/hackerspace.gr/ssl.key",
      dest: "{{ ssl_cert_key }}"
      }
  notify: restart nginx

- name: Add nginx ports to firewall
  firewalld: port={{ item }} zone=public permanent=true state=enabled
  with_items:
    - 80/tcp
    - 443/tcp
  notify: restart firewalld

- name: Enable nginx service
  service: name=nginx state=started enabled=yes
