---
- hosts: jupiter
  become: true

  vars:
    - domain: 'jupiter.libreops.cc'
    - mail_domain: 'jupiter.libreops.cc'
    - jabber_domain: 'gnu.gr'
    - mailman_domain: 'diskuti.gr'
    - mailman_desc: 'diskuti - Online communication tools for grassroots communities'
    - mailman_logo: 'https://diskuti.gr/static/img/diskuti.png'
    - mumble_domain: mumble.libreops.cc

  roles:
    - common
    - firewalld
    - postfix
    - mariadb
    - nginx
    - mailman
    - jabber
    - murmur
    - pad
    - backup
