---
- hosts: jupiter
  become: true

  vars:
    - mail_domain: 'jupiter.hackerspace.gr'
    - jabber_domain: 'gnu.gr'
    - mailman_domain: 'diskuti.gr'
    - mailman_desc: 'diskuti - Online communication tools for grassroots communities'
    - mailman_logo: 'https://diskuti.gr/static/img/diskuti.png'

  roles:
    - common
    - firewalld
    - postfix
    - mariadb
    - nginx
    - mailman
    - jabber
    - murmur
    - pad
    - backup
