---
# tasks file for mariadb
- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel

- name: Ensure MariaDB is started and enabled on boot
  service: name=mariadb state=started enabled=yes

- include: secure-installation.yml tags=database
