---
# tasks file for common
- include_vars: private.yml

- name: Install EPEL repo
  yum: name=epel-release state=present

- name: Install system dependencies
  yum: name={{ item }} state=present
  with_items:
    - vim
    - tar
    - policycoreutils-python
    - git
    - bash-completion
    - mlocate
    - certbot

- name: Update admins
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    exclusive: yes
    key: "{{ admins|join('\n') }}"
