---
# tasks file for common
- include_vars: private.yml

- name: Install EPEL repo
  yum: name=epel-release state=present
  tags:
    - yum
    - pkg
    - epel

- name: Install system dependencies
  yum: name={{ item }} state=present
  with_items:
    - vim
    - tar
    - policycoreutils-python
    - git
  tags:
    - yum
    - pkg

- name: Add deploy group
  group: name=deploy state=present

- name: Add admins
  user: name={{ item.name }} group={{ item.name }} groups=wheel state=present
  with_items: admins

- name: Add ssh keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: admins
