---
# tasks file for common

- name: Install EPEL repo
  yum: name=epel-release state=present
  tags:
    - yum
    - pkg
    - epel

- name: Install system dependencies
  yum: name={{ item }} state=present
  with_items:
    - vim
    - tar
    - policycoreutils-python
  tags:
    - yum
    - pkg

- include: "sshd.yml"
