---
- include_vars: private.yml

- name: Install pad system requirements
  yum: name={{ item }} state=present
  with_items:
    - gzip
    - openssl-devel
    - curl
    - gcc
    - nodejs
    - npm

#- name: install the 'Development tools' package group
#  yum: name="@Development tools" state=present

- name: Add pad group
  group: name=pad state=present

- name: Add pad user
  user: name=pad group=pad state=present

- name: Create pad directories
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: pad
    group: pad
    recurse: yes

- name: Pull sources from the repository
  become_user: pad
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir }}"
    version: "{{ pad_tag }}"
    force: yes
    update: yes

- name: Install pad dependencies
  become_user: pad
  command: bin/installDeps.sh chdir={{ app_dir }} creates={{ app_dir }}/.node-gyp

- name: Install plugins
  become_user: pad
  npm:
    name: {{ item }}
    path: "{{ app_dir }}"
    state: present
  with_items:
    - ep_padlist
    - ep_disableChat
    - ep_spellcheck

- name: Create pad database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    collation: utf8_unicode_ci
    encoding: utf8

- name: Create mysql pad user and give privileges
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    state: present
    priv: "{{ db_name }}.*:ALL"
    host: "localhost"

- name: Copy pad settings file
  template:
    src: "settings.json.j2"
    dest: "{{ app_dir }}/settings.json"
    owner: pad
    group: pad
    mode: 0600

- name: Add port to selinux http policy
  command: semanage port -a -t http_port_t -p tcp {{ siteport }}
  tags:
    - selinux
    - pad

- name: Copy pad systemd service file
  template:
    src:  'pad.service.j2'
    dest: '/etc/systemd/system/pad-{{ sitename }}.service'
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload

- name: Copy pad nginx vhost conf
  template:
    src: "pad.conf.j2"
    dest: "/etc/nginx/conf.d/pad.conf"
    owner: root
    group: root
    mode: 644

- name: Enable pad service
  service: name=pad-{{ sitename }} state=started enabled=yes

- name: Restart pad and nginx
  service: name=pad-{{ sitename }} state=restarted enabled=yes
  notify:
    - restart nginx
