---
- name: Check for updates, do not install
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - command: /usr/bin/yum check-update
      register: update
      ignore_errors: yes
      changed_when: false
    - debug: var=update.stdout_lines
